resources:
  repositories:
  - repository: dockerfiles
    type: github
    endpoint: martamazurkiewicz
    name: martamazurkiewicz/dockerfiles
    ref: main

parameters:
- name: purge_volumes
  displayName: Purge volumes
  type: boolean
  default: false 

trigger:
- none

jobs:

- job: build
  displayName: build
  pool: 
    name: Default
  steps:
  - checkout: self
  - checkout: dockerfiles
  - script: ls -al $(Build.SourcesDirectory)
  - task: CopyFiles@2
    displayName: 'Copy dockerfiles into pipeline'
    inputs:
      contents: '$(Build.SourcesDirectory)/dockerfiles/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - publish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish dockerfiles for later use'
    artifact: dockerfiles

- job: build_containers
  displayName: 'build containers'
  dependsOn: build
  pool:
    name: Default
  steps:
  - download: current
    artifact: dockerfiles
  - script: |
      echo "List all dockerfiles"
      ls "$(Pipeline.Workspace)/dockerfiles/"
  - script: echo "##vso[task.setvariable variable=containers;]ls $(Pipeline.Workspace)/dockerfiles"
  - script: |
      echo "List all dockerfiles"
      echo "$(containers)"
  # - template: build_container.yaml
  #   parameters:
  #     containers: $(containers)
